name: AllAPILoader
main: TheNewHEROBRINE\AllAPILoader\Main
version: 1.0.0
api: [3.0.0-ALPHA12,3.0.0-ALPHA13,3.0.0-ALPHA14,3.0.0-ALPHA15]
author: TheNewHEROBRINE
description: Makes the server load every plugin regardless of the API version
load: STARTUP
softdepend: ["DevTools", "FolderPluginLoader"]
